services:
  postgres:
    image: 'postgres:latest'
    restart: always
    environment:
      - 'POSTGRES_DB=ecommerce'
      - 'POSTGRES_PASSWORD=dev2025'
      - 'POSTGRES_USER=postgres'
    ports:
      - '5432'
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:

